# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img_dir',
            field=models.ImageField(help_text='Note Picture', upload_to='origin/'),
        ),
    ]
